#!/usr/bin/env python3
"""
Per-metal offsets for NIST-calibrated predictions.
Generated by nist_backsolve Phase 4.
Apply: corrected_log_K = raw_log_K - offset[metal]
"""

METAL_OFFSETS = {
    "Cu(II)": -0.12,
    "Ni(II)": 1.194,
    "Zn(II)": -0.295,
    "Co(II)": 1.694,
    "Cd(II)": 0.301,
    "Ca(II)": 0.703,
    "Mn(II)": 1.887,
    "Pb(II)": -2.042,
    "Mg(II)": 1.328,
    "Sr(II)": 2.055,
    "Ag(I)": -0.938,
    "Ba(II)": 4.858,
    "La(III)": 0.903,
    "Gd(III)": 1.867,
    "Eu(III)": 2.514,
    "Nd(III)": 3.58,
    "Dy(III)": 4.234,
    "Lu(III)": 1.169,
    "Fe(III)": -8.664,
    "Hg(II)": -6.842,
    "Yb(III)": 1.915,
    "Ce(III)": 1.735,
    "Al(III)": -3.088,
    "Fe(II)": 1.698,
    "Ga(III)": -9.057,
    "K(I)": -0.26,
    "Na(I)": -0.157,
    "In(III)": -5.242,
    "Cu(I)": -3.055,
    "Li(I)": -1.217,
    "VO(II)": -0.707,
    "Tl(I)": 2.669,
    "Th(IV)": 2.192,
    "Rb(I)": 0.445,
    "Cs(I)": 0.552,
    "Sc(III)": -0.233,
    "Sn(II)": -3.233,
    "Cr(III)": -1.5,
    "Pd(II)": -21.686,
    "U(IV)": 3.816,
    "Bi(III)": -12.097,
    "V(III)": 2.51
}

def apply_offset(metal_formula, log_k_raw):
    """Correct raw log K prediction with per-metal offset."""
    return log_k_raw - METAL_OFFSETS.get(metal_formula, 0.0)