"""
knowledge/dnazyme_library.py - Curated DNAzyme and DNA motif library.

Real sequences, real Kd values, real selectivity data from published literature.
Each entry includes the modification needed to convert from sensor to capture mode.

Sources: Lu Lab (UIUC), Santoro & Joyce, Ono & Togashi.
"""

DNAZYME_LIBRARY = [
    {
        "id": "dnz-gr5-001",
        "name": "GR-5 DNAzyme",
        "modality": "dnazyme",
        "sequence": "5\'-CATCTCTTCTCCGAGCCGGTCGAAATAGTGAGT-3\'",
        "primary_target": "Pb2+",
        "target_aliases": ["lead", "pb"],
        "kd_um": 0.05,
        "kd_confidence": "measured_fluorescence",
        "stoichiometry": "1:1",
        "ph_range": (5.0, 9.0),
        "temp_range_c": (4, 45),
        "ionic_strength_range_mm": (10, 500),
        "capture_modification": "2\'-OMe at rA cleavage site disables cleavage, retains Pb2+ binding",
        "capture_validated": False,
        "validation_tier": 3,
        "selectivity": [
            {"competitor": "Ca2+", "competitor_alias": "calcium", "fold": 40000},
            {"competitor": "Mg2+", "competitor_alias": "magnesium", "fold": 10000},
            {"competitor": "Zn2+", "competitor_alias": "zinc", "fold": 100},
            {"competitor": "Mn2+", "competitor_alias": "manganese", "fold": 1000},
            {"competitor": "Co2+", "competitor_alias": "cobalt", "fold": 1000},
        ],
        "conjugation_handles": ["5\'-amine (NHS-amine, SPAAC)", "3\'-thiol (maleimide-thiol)"],
        "incompatibilities": [
            {"condition": "EDTA buffer", "effect": "strips target metal", "severity": "fatal"},
            {"condition": "pH below 4", "effect": "DNA depurination", "severity": "fatal"},
        ],
        "doi": "10.1021/ja0340534",
        "year": 2000,
        "lab": "Lu Lab, UIUC",
        "notes": "Gold standard Pb2+ DNAzyme sensor. Most widely studied. >40,000-fold selectivity over Ca2+.",
        "environmental_tested": True,
        "environmental_notes": "Functional in Lake Michigan water samples with minor interference.",
    },
    {
        "id": "dnz-817-001",
        "name": "8-17 DNAzyme",
        "modality": "dnazyme",
        "sequence": "5\'-TTTTTTAGCTGATCTTCCA-rA-GGTTCTCC-3\'",
        "primary_target": "Pb2+",
        "target_aliases": ["lead", "pb"],
        "kd_um": 0.1,
        "kd_confidence": "measured_fluorescence",
        "stoichiometry": "1:1",
        "ph_range": (5.5, 9.0),
        "temp_range_c": (10, 40),
        "ionic_strength_range_mm": (50, 300),
        "capture_modification": "2\'-OMe at rA cleavage site",
        "capture_validated": False,
        "validation_tier": 3,
        "selectivity": [
            {"competitor": "Zn2+", "competitor_alias": "zinc", "fold": 10},
            {"competitor": "Ca2+", "competitor_alias": "calcium", "fold": 5000},
        ],
        "conjugation_handles": ["5\'-amine (NHS-amine)", "3\'-biotin (streptavidin)"],
        "incompatibilities": [
            {"condition": "EDTA buffer", "effect": "strips target metal", "severity": "fatal"},
            {"condition": "high Zn2+", "effect": "cross-reactivity at mM Zn2+ levels", "severity": "reduces_performance"},
        ],
        "doi": "10.1016/S0009-2614(99)01016-9",
        "year": 1997,
        "lab": "Santoro & Joyce, Scripps",
        "notes": "First RNA-cleaving DNAzyme. Also has Zn2+ activity - lower selectivity than GR-5 for Pb2+.",
        "environmental_tested": False,
        "environmental_notes": "",
    },
    {
        "id": "dnz-ag10c-001",
        "name": "Ag10c DNAzyme",
        "modality": "dnazyme",
        "sequence": "5\'-CCCCCTACTACTCTTAACTGATG-rA-GGAAGAGATG-3\'",
        "primary_target": "Ag+",
        "target_aliases": ["silver", "ag"],
        "kd_um": 0.5,
        "kd_confidence": "measured_fluorescence",
        "stoichiometry": "1:1",
        "ph_range": (5.0, 8.5),
        "temp_range_c": (15, 40),
        "ionic_strength_range_mm": (20, 200),
        "capture_modification": "2\'-OMe at rA cleavage site",
        "capture_validated": False,
        "validation_tier": 2,
        "selectivity": [
            {"competitor": "Cu2+", "competitor_alias": "copper", "fold": 100},
            {"competitor": "Hg2+", "competitor_alias": "mercury", "fold": 50},
            {"competitor": "Pb2+", "competitor_alias": "lead", "fold": 200},
        ],
        "conjugation_handles": ["5\'-amine (NHS-amine)"],
        "incompatibilities": [
            {"condition": "EDTA buffer", "effect": "strips target metal", "severity": "fatal"},
            {"condition": "chloride-rich", "effect": "AgCl precipitation reduces free Ag+", "severity": "reduces_performance"},
        ],
        "doi": "10.1002/anie.201411180",
        "year": 2014,
        "lab": "Lu Lab, UIUC",
        "notes": "First Ag+-specific DNAzyme. Useful for silver detection in environmental and consumer products.",
        "environmental_tested": False,
        "environmental_notes": "",
    },
    {
        "id": "dnz-ce13d-001",
        "name": "Ce13d DNAzyme",
        "modality": "dnazyme",
        "sequence": "5\'-GTTGGGATCGATTTTT-rA-GGTTCGATCAATCGT-3\'",
        "primary_target": "Ce3+",
        "target_aliases": ["cerium", "ce", "lanthanide", "rare earth", "ree"],
        "kd_um": 0.01,
        "kd_confidence": "measured_fluorescence",
        "stoichiometry": "1:1",
        "ph_range": (5.5, 7.5),
        "temp_range_c": (15, 37),
        "ionic_strength_range_mm": (50, 300),
        "capture_modification": "2\'-OMe at rA cleavage site",
        "capture_validated": False,
        "validation_tier": 2,
        "selectivity": [
            {"competitor": "Pb2+", "competitor_alias": "lead", "fold": 500},
            {"competitor": "Ca2+", "competitor_alias": "calcium", "fold": 10000},
            {"competitor": "Y3+", "competitor_alias": "yttrium", "fold": 2},
        ],
        "conjugation_handles": ["5\'-amine (NHS-amine)"],
        "incompatibilities": [
            {"condition": "phosphate buffer", "effect": "lanthanide-phosphate precipitation", "severity": "fatal"},
            {"condition": "pH above 8", "effect": "lanthanide hydroxide precipitation", "severity": "fatal"},
        ],
        "doi": "10.1021/jacs.5b01904",
        "year": 2015,
        "lab": "Lu Lab, UIUC",
        "notes": "Responds to all trivalent lanthanides. General REE sensor. Extremely high sensitivity (nM range).",
        "environmental_tested": False,
        "environmental_notes": "",
    },
    {
        "id": "dnz-39e-001",
        "name": "39E DNAzyme",
        "modality": "dnazyme",
        "sequence": "5\'-CAGCCAAACTTAAACAGACTTACTCTCATATGATT-rA-GGAAGAGATG-3\'",
        "primary_target": "UO2(2+)",
        "target_aliases": ["uranyl", "uranium", "uo2"],
        "kd_um": 0.0001,
        "kd_confidence": "measured_fluorescence",
        "stoichiometry": "1:1",
        "ph_range": (5.0, 7.0),
        "temp_range_c": (15, 37),
        "ionic_strength_range_mm": (50, 300),
        "capture_modification": "2\'-OMe at rA cleavage site",
        "capture_validated": False,
        "validation_tier": 3,
        "selectivity": [
            {"competitor": "Pb2+", "competitor_alias": "lead", "fold": 1000000},
            {"competitor": "Th4+", "competitor_alias": "thorium", "fold": 100},
            {"competitor": "Ca2+", "competitor_alias": "calcium", "fold": 1000000},
        ],
        "conjugation_handles": ["5\'-amine (NHS-amine)"],
        "incompatibilities": [
            {"condition": "carbonate-rich", "effect": "UO2 forms soluble carbonate complexes", "severity": "reduces_performance"},
        ],
        "doi": "10.1073/pnas.0709316104",
        "year": 2007,
        "lab": "Lu Lab, UIUC",
        "notes": "Best-in-class uranyl sensor. 45 pM detection limit. Tested at Hanford nuclear site groundwater. 1-million-fold selectivity.",
        "environmental_tested": True,
        "environmental_notes": "Functional in real groundwater from uranium mining sites.",
    },
    {
        "id": "dnz-naa43-001",
        "name": "NaA43 DNAzyme",
        "modality": "dnazyme",
        "sequence": "5\'-AAGAAAGCGACTGCATTTTTGGAGTCTCCCGT-rA-GGTCAAATTTGCC-3\'",
        "primary_target": "Na+",
        "target_aliases": ["sodium", "na"],
        "kd_um": 135000.0,
        "kd_confidence": "measured_fluorescence",
        "stoichiometry": "1:1",
        "ph_range": (6.0, 8.0),
        "temp_range_c": (15, 37),
        "ionic_strength_range_mm": (0, 1000),
        "capture_modification": "2\'-OMe at rA cleavage site",
        "capture_validated": False,
        "validation_tier": 2,
        "selectivity": [
            {"competitor": "K+", "competitor_alias": "potassium", "fold": 10000},
            {"competitor": "Li+", "competitor_alias": "lithium", "fold": 390},
            {"competitor": "Ca2+", "competitor_alias": "calcium", "fold": 10000},
        ],
        "conjugation_handles": ["5\'-amine (NHS-amine)"],
        "incompatibilities": [],
        "doi": "10.1021/jacs.5b00504",
        "year": 2015,
        "lab": "Lu Lab, UIUC",
        "notes": "First Na+-specific DNAzyme. 10,000-fold selectivity over K+. High Kd but Na+ is abundant.",
        "environmental_tested": False,
        "environmental_notes": "",
    },
    {
        "id": "mot-t-hg-t-001",
        "name": "T-Hg2+-T Mismatch Pair",
        "modality": "dna_motif",
        "sequence": "Thymine-thymine mismatch in DNA duplex",
        "primary_target": "Hg2+",
        "target_aliases": ["mercury", "hg"],
        "kd_um": 1.0,
        "kd_confidence": "measured_fluorescence",
        "stoichiometry": "1:1 per T-T mismatch",
        "ph_range": (5.0, 9.0),
        "temp_range_c": (4, 50),
        "ionic_strength_range_mm": (10, 500),
        "capture_modification": None,
        "capture_validated": True,
        "validation_tier": 4,
        "selectivity": [
            {"competitor": "Ag+", "competitor_alias": "silver", "fold": 100},
            {"competitor": "Pb2+", "competitor_alias": "lead", "fold": 1000},
            {"competitor": "Cu2+", "competitor_alias": "copper", "fold": 500},
        ],
        "conjugation_handles": ["5\'-amine (NHS-amine, SPAAC)", "3\'-thiol (maleimide-thiol, gold-thiol)"],
        "incompatibilities": [
            {"condition": "thiol-rich", "effect": "thiols compete for Hg2+ binding", "severity": "reduces_performance"},
            {"condition": "EDTA buffer", "effect": "chelates Hg2+", "severity": "fatal"},
        ],
        "doi": "10.1002/anie.200453775",
        "year": 2004,
        "lab": "Ono & Togashi",
        "notes": "Capture-ready: no cleavage to disable. Multiple T-T mismatches increase capacity. Foundational Hg2+ motif.",
        "environmental_tested": True,
        "environmental_notes": "Functional mercury detection in lake water.",
    },
    {
        "id": "mot-c-ag-c-001",
        "name": "C-Ag+-C Mismatch Pair",
        "modality": "dna_motif",
        "sequence": "Cytosine-cytosine mismatch in DNA duplex",
        "primary_target": "Ag+",
        "target_aliases": ["silver", "ag"],
        "kd_um": 2.0,
        "kd_confidence": "measured_fluorescence",
        "stoichiometry": "1:1 per C-C mismatch",
        "ph_range": (5.0, 8.5),
        "temp_range_c": (4, 45),
        "ionic_strength_range_mm": (10, 300),
        "capture_modification": None,
        "capture_validated": True,
        "validation_tier": 3,
        "selectivity": [
            {"competitor": "Hg2+", "competitor_alias": "mercury", "fold": 50},
            {"competitor": "Cu2+", "competitor_alias": "copper", "fold": 200},
            {"competitor": "Pb2+", "competitor_alias": "lead", "fold": 500},
        ],
        "conjugation_handles": ["5\'-amine (NHS-amine)", "3\'-thiol (maleimide-thiol, gold-thiol)"],
        "incompatibilities": [
            {"condition": "chloride-rich", "effect": "AgCl precipitation reduces free Ag+", "severity": "reduces_performance"},
        ],
        "doi": "10.1002/anie.200800370",
        "year": 2008,
        "lab": "Ono et al.",
        "notes": "Capture-ready. Complementary to T-Hg-T system - can detect Ag+ and Hg2+ orthogonally in same sample.",
        "environmental_tested": False,
        "environmental_notes": "",
    },
]
