"""
knowledge/peptide_library.py - Curated peptide chelator and metal-binding peptide library.

Real sequences with known metal affinities from published literature.
Peptides bridge the gap between small-molecule chelators and designed proteins:
cheaper than proteins, more selective than chelators, biodegradable, easy to order.
"""

PEPTIDE_LIBRARY = [
    # ── Phytochelatins ───────────────────────────────────────────
    {
        "name": "Phytochelatin PC2",
        "sequence": "(gEC)2G",
        "full_sequence": "gamma-Glu-Cys-gamma-Glu-Cys-Gly",
        "class": "phytochelatin",
        "length": 5,
        "donor_atoms": ["S", "N", "O"],
        "donor_type": "soft",
        "primary_targets": ["Cd2+", "Pb2+", "Hg2+", "As3+", "Cu2+", "Zn2+"],
        "target_aliases": {"cadmium": "Cd2+", "lead": "Pb2+", "mercury": "Hg2+",
                          "arsenic": "As3+", "copper": "Cu2+", "zinc": "Zn2+"},
        "kd_data": {"Cd2+": 0.1, "Pb2+": 1.0, "Hg2+": 0.01, "Cu2+": 0.5},
        "ph_range": (4.0, 8.0),
        "temp_stable_c": (4, 60),
        "cost_per_mg": "$5",
        "synthesis": "Solid-phase peptide synthesis, any peptide service",
        "community_lab": True,
        "reusability": 30,
        "notes": "Natural plant defense peptide. Thiol-rich. Excellent Cd2+ and Hg2+ binding. Biodegradable.",
        "doi": "10.1146/annurev.arplant.49.1.643",
        "year": 1998,
        "environmental_tested": True,
        "conjugation": ["N-terminal amine (NHS coupling)", "C-terminal carboxylate (EDC/NHS)"],
    },
    {
        "name": "Phytochelatin PC3",
        "sequence": "(gEC)3G",
        "full_sequence": "gamma-Glu-Cys-gamma-Glu-Cys-gamma-Glu-Cys-Gly",
        "class": "phytochelatin",
        "length": 7,
        "donor_atoms": ["S", "N", "O"],
        "donor_type": "soft",
        "primary_targets": ["Cd2+", "Pb2+", "Hg2+", "As3+", "Cu2+"],
        "target_aliases": {"cadmium": "Cd2+", "lead": "Pb2+", "mercury": "Hg2+",
                          "arsenic": "As3+", "copper": "Cu2+"},
        "kd_data": {"Cd2+": 0.01, "Pb2+": 0.5, "Hg2+": 0.001},
        "ph_range": (4.0, 8.0),
        "temp_stable_c": (4, 60),
        "cost_per_mg": "$8",
        "synthesis": "Solid-phase peptide synthesis",
        "community_lab": True,
        "reusability": 25,
        "notes": "Longer phytochelatin, 3 Cys thiols. Higher capacity and affinity than PC2. Gold standard for Cd2+.",
        "doi": "10.1146/annurev.arplant.49.1.643",
        "year": 1998,
        "environmental_tested": True,
        "conjugation": ["N-terminal amine (NHS coupling)", "C-terminal carboxylate (EDC/NHS)"],
    },

    # ── Metallothionein-derived peptides ─────────────────────────
    {
        "name": "MT alpha-domain peptide",
        "sequence": "KSCCSCCPVGCAKCSQGCICKEASDK",
        "full_sequence": "Lys-Ser-Cys-Cys-Ser-Cys-Cys-Pro-Val-Gly-Cys-Ala-Lys-Cys-Ser-Gln-Gly-Cys-Ile-Cys-Lys-Glu-Ala-Ser-Asp-Lys",
        "class": "metallothionein",
        "length": 26,
        "donor_atoms": ["S"],
        "donor_type": "soft",
        "primary_targets": ["Zn2+", "Cd2+", "Cu+", "Hg2+", "Pb2+"],
        "target_aliases": {"zinc": "Zn2+", "cadmium": "Cd2+", "copper": "Cu+",
                          "mercury": "Hg2+", "lead": "Pb2+"},
        "kd_data": {"Zn2+": 0.01, "Cd2+": 0.001, "Cu+": 0.0001},
        "ph_range": (5.0, 8.5),
        "temp_stable_c": (4, 50),
        "cost_per_mg": "$15",
        "synthesis": "Solid-phase peptide synthesis, longer peptide surcharge",
        "community_lab": False,
        "reusability": 15,
        "notes": "Human MT-2 alpha domain. 9 Cys residues, coordinates 4 Zn/Cd in Cys4 clusters. Extremely high affinity for soft metals.",
        "doi": "10.1021/cr800556u",
        "year": 2009,
        "environmental_tested": False,
        "conjugation": ["N-terminal amine (NHS coupling)", "Lys side chains (NHS coupling)"],
    },

    # ── Hexahistidine and His-rich peptides ──────────────────────
    {
        "name": "His6 tag",
        "sequence": "HHHHHH",
        "full_sequence": "His-His-His-His-His-His",
        "class": "his_tag",
        "length": 6,
        "donor_atoms": ["N"],
        "donor_type": "borderline",
        "primary_targets": ["Ni2+", "Cu2+", "Zn2+", "Co2+"],
        "target_aliases": {"nickel": "Ni2+", "copper": "Cu2+", "zinc": "Zn2+", "cobalt": "Co2+"},
        "kd_data": {"Ni2+": 10.0, "Cu2+": 1.0, "Zn2+": 50.0, "Co2+": 100.0},
        "ph_range": (7.0, 9.0),
        "temp_stable_c": (4, 80),
        "cost_per_mg": "$2",
        "synthesis": "Commodity peptide, any supplier",
        "community_lab": True,
        "reusability": 100,
        "notes": "The workhorse of protein purification. Extremely well characterized. Imidazole elution for clean release. Billions of uses in IMAC.",
        "doi": "10.1016/0022-2836(86)90137-7",
        "year": 1986,
        "environmental_tested": False,
        "conjugation": ["N-terminal amine (NHS coupling)", "C-terminal carboxylate (EDC/NHS)"],
    },
    {
        "name": "His8 tag (extended)",
        "sequence": "HHHHHHHH",
        "full_sequence": "His-His-His-His-His-His-His-His",
        "class": "his_tag",
        "length": 8,
        "donor_atoms": ["N"],
        "donor_type": "borderline",
        "primary_targets": ["Ni2+", "Cu2+", "Zn2+", "Co2+"],
        "target_aliases": {"nickel": "Ni2+", "copper": "Cu2+", "zinc": "Zn2+", "cobalt": "Co2+"},
        "kd_data": {"Ni2+": 1.0, "Cu2+": 0.1, "Zn2+": 10.0},
        "ph_range": (7.0, 9.0),
        "temp_stable_c": (4, 80),
        "cost_per_mg": "$3",
        "synthesis": "Commodity peptide",
        "community_lab": True,
        "reusability": 100,
        "notes": "Extended His-tag. Tighter binding than His6. Same imidazole elution. Slightly better for Ni2+ capture.",
        "doi": "10.1016/j.chroma.2003.12.040",
        "year": 2004,
        "environmental_tested": False,
        "conjugation": ["N-terminal amine (NHS coupling)", "C-terminal carboxylate (EDC/NHS)"],
    },

    # ── Metal-binding peptides from SELEX/phage display ──────────
    {
        "name": "Pb-binding peptide (PbBP1)",
        "sequence": "TNTLSNN",
        "full_sequence": "Thr-Asn-Thr-Leu-Ser-Asn-Asn",
        "class": "selected_peptide",
        "length": 7,
        "donor_atoms": ["O", "N"],
        "donor_type": "hard",
        "primary_targets": ["Pb2+"],
        "target_aliases": {"lead": "Pb2+"},
        "kd_data": {"Pb2+": 20.0},
        "ph_range": (5.0, 8.0),
        "temp_stable_c": (4, 60),
        "cost_per_mg": "$3",
        "synthesis": "Standard SPPS",
        "community_lab": True,
        "reusability": 50,
        "notes": "Phage display-selected Pb2+ binding peptide. Moderate affinity but good selectivity.",
        "doi": "10.1021/es034408q",
        "year": 2004,
        "environmental_tested": False,
        "conjugation": ["N-terminal amine (NHS coupling)", "C-terminal carboxylate (EDC/NHS)"],
    },
    {
        "name": "As-binding peptide (AsBP1)",
        "sequence": "DVLFNTMGGSHGRCM",
        "full_sequence": "Asp-Val-Leu-Phe-Asn-Thr-Met-Gly-Gly-Ser-His-Gly-Arg-Cys-Met",
        "class": "selected_peptide",
        "length": 15,
        "donor_atoms": ["S", "N", "O"],
        "donor_type": "soft",
        "primary_targets": ["As3+", "As5+"],
        "target_aliases": {"arsenic": "As3+"},
        "kd_data": {"As3+": 5.0},
        "ph_range": (5.0, 8.0),
        "temp_stable_c": (4, 50),
        "cost_per_mg": "$10",
        "synthesis": "SPPS, Cys and Met require care",
        "community_lab": True,
        "reusability": 20,
        "notes": "Phage display-selected As3+ binding peptide. Contains Cys and Met for soft donor coordination.",
        "doi": "10.1021/es049092i",
        "year": 2005,
        "environmental_tested": False,
        "conjugation": ["N-terminal amine (NHS coupling)"],
    },

    # ── Cys-rich designed peptides ───────────────────────────────
    {
        "name": "Cys4-Gly peptide (Hg capture)",
        "sequence": "GCGCGCGC",
        "full_sequence": "Gly-Cys-Gly-Cys-Gly-Cys-Gly-Cys",
        "class": "designed_peptide",
        "length": 8,
        "donor_atoms": ["S"],
        "donor_type": "soft",
        "primary_targets": ["Hg2+", "Au3+", "Ag+", "Cd2+", "Pb2+"],
        "target_aliases": {"mercury": "Hg2+", "gold": "Au3+", "silver": "Ag+",
                          "cadmium": "Cd2+", "lead": "Pb2+"},
        "kd_data": {"Hg2+": 0.001, "Au3+": 0.01, "Ag+": 0.1, "Cd2+": 0.1},
        "ph_range": (4.0, 8.0),
        "temp_stable_c": (4, 50),
        "cost_per_mg": "$5",
        "synthesis": "Standard SPPS, handle under N2 to prevent disulfide",
        "community_lab": True,
        "reusability": 15,
        "notes": "Simple alternating Cys-Gly. 4 thiol donors for soft metal coordination. Cheap, effective, biodegradable. Oxidation-sensitive.",
        "doi": "10.1016/j.bios.2012.05.034",
        "year": 2012,
        "environmental_tested": False,
        "conjugation": ["N-terminal amine (NHS coupling)", "C-terminal carboxylate (EDC/NHS)"],
    },
]


# ── Aptamer library ──────────────────────────────────────────────

APTAMER_LIBRARY = [
    {
        "name": "Ars-3 arsenic aptamer",
        "sequence": "5\'-GGTAATACGACTCACTATAGGGAGATACCAGCTTATTCAATT-3\'",
        "modality": "dna_aptamer",
        "primary_target": "As3+",
        "target_aliases": ["arsenic", "as"],
        "kd_um": 7.0,
        "ph_range": (6.0, 8.0),
        "selectivity": [
            {"competitor": "phosphate", "fold": 10},
        ],
        "notes": "SELEX-selected As(III) aptamer. Binds arsenite without cleaving. No modification needed for capture.",
        "doi": "10.1021/ac101559q",
        "year": 2010,
        "capture_ready": True,
        "environmental_tested": False,
        "cost_per_synthesis": "$40",
        "conjugation": ["5\'-amine (NHS)", "3\'-biotin (streptavidin)"],
    },
    {
        "name": "Cd-aptamer (Cd-4)",
        "sequence": "5\'-GAATTCCCACGCACTCGGCTACATGAGAATCAGCTTATTCAATTG-3\'",
        "modality": "dna_aptamer",
        "primary_target": "Cd2+",
        "target_aliases": ["cadmium", "cd"],
        "kd_um": 0.35,
        "ph_range": (6.5, 8.0),
        "selectivity": [
            {"competitor": "Zn2+", "competitor_alias": "zinc", "fold": 50},
            {"competitor": "Pb2+", "competitor_alias": "lead", "fold": 100},
        ],
        "notes": "SELEX-selected Cd2+ aptamer. Sub-micromolar affinity. Good Zn/Cd discrimination.",
        "doi": "10.1016/j.aca.2012.07.011",
        "year": 2012,
        "capture_ready": True,
        "environmental_tested": False,
        "cost_per_synthesis": "$50",
        "conjugation": ["5\'-amine (NHS)", "3\'-thiol (maleimide)"],
    },
    {
        "name": "Hg-aptamer (thymine-rich)",
        "sequence": "5\'-TTCTTTCTTCCCCTTGTTTGTT-3\'",
        "modality": "dna_aptamer",
        "primary_target": "Hg2+",
        "target_aliases": ["mercury", "hg"],
        "kd_um": 0.05,
        "ph_range": (5.5, 8.5),
        "selectivity": [
            {"competitor": "Ag+", "competitor_alias": "silver", "fold": 200},
            {"competitor": "Pb2+", "competitor_alias": "lead", "fold": 1000},
        ],
        "notes": "Thymine-rich aptamer exploiting T-Hg-T chemistry in folded structure. Very high affinity.",
        "doi": "10.1002/anie.200700269",
        "year": 2007,
        "capture_ready": True,
        "environmental_tested": True,
        "cost_per_synthesis": "$30",
        "conjugation": ["5\'-amine (NHS)", "3\'-biotin (streptavidin)"],
    },
]
